## **Muhammad Daffa Putra Mahardika**
## **2009106036**
## **Posttest 7**

In [1]:
import tensorflow as tf

# 1) Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [3]:
# Tensor (5,5) nilai Random
random_tensor = tf.Variable(tf.random.normal([5,5], mean=5, stddev=1, dtype=tf.float32, seed=30))
random_tensor.read_value().numpy()

array([[4.613833 , 5.084854 , 2.2378907, 4.858652 , 5.7292266],
       [4.025921 , 4.714781 , 5.1130815, 5.4879904, 5.9685326],
       [5.573825 , 3.2475438, 4.462555 , 4.476487 , 4.070874 ],
       [4.894192 , 4.009323 , 4.6798654, 4.883642 , 4.827503 ],
       [5.1000853, 5.704425 , 5.6030755, 4.4744415, 5.4573894]],
      dtype=float32)

# 2) Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [4]:
# Tensor (5,5) nilai bilangan Prima
list = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,67,71],[73,79,83,89,97]]

In [5]:
prime_tensor = tf.Variable((tf.convert_to_tensor(list, dtype=tf.float32)))
prime_tensor.read_value().numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

# 3) Tampilkan dimensi dari kedua variable tersebut

In [6]:
# Dimensi kedua Variabel
print(random_tensor.shape)
print(prime_tensor.shape)

(5, 5)
(5, 5)


# 4) Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [7]:
# Operator Pertambahan
tf.add(random_tensor,prime_tensor).numpy()

array([[  6.613833 ,   8.084854 ,   7.2378907,  11.858652 ,  16.729227 ],
       [ 17.02592  ,  21.71478  ,  24.113081 ,  28.487991 ,  34.968533 ],
       [ 36.573826 ,  40.247543 ,  45.462555 ,  47.476486 ,  51.070873 ],
       [ 57.89419  ,  63.009323 ,  65.67986  ,  71.883644 ,  75.8275   ],
       [ 78.10008  ,  84.70442  ,  88.60307  ,  93.47444  , 102.45739  ]],
      dtype=float32)

In [8]:
# Operator Pengurangan
tf.subtract(random_tensor,prime_tensor).numpy()

array([[  2.613833 ,   2.0848541,  -2.7621093,  -2.141348 ,  -5.2707734],
       [ -8.974079 , -12.285219 , -13.886919 , -17.512009 , -23.031467 ],
       [-25.426174 , -33.752457 , -36.537445 , -38.523514 , -42.929127 ],
       [-48.10581  , -54.990677 , -56.320133 , -62.116356 , -66.1725   ],
       [-67.89992  , -73.29558  , -77.39693  , -84.52556  , -91.54261  ]],
      dtype=float32)

In [9]:
# Operator Perkalian
tf.multiply(random_tensor,prime_tensor).numpy()

array([[  9.227666,  15.254562,  11.189453,  34.010567,  63.021492],
       [ 52.33697 ,  80.151276,  97.148544, 126.22378 , 173.08745 ],
       [172.78857 , 120.15912 , 182.96475 , 192.48895 , 191.33109 ],
       [259.39218 , 236.55006 , 285.4718  , 327.20404 , 342.75272 ],
       [372.3062  , 450.64957 , 465.05527 , 398.22528 , 529.36676 ]],
      dtype=float32)

In [10]:
# Operator Pembagian
tf.divide(random_tensor,prime_tensor).numpy()

array([[2.3069165 , 1.6949514 , 0.44757813, 0.69409317, 0.5208388 ],
       [0.3096862 , 0.27734005, 0.26910955, 0.23860827, 0.20581147],
       [0.17980081, 0.08777145, 0.10884281, 0.10410435, 0.08661435],
       [0.09234325, 0.06795463, 0.07671911, 0.07289018, 0.067993  ],
       [0.06986418, 0.07220791, 0.06750693, 0.05027463, 0.05626174]],
      dtype=float32)

In [11]:
# Operator Pemangkatan
tf.pow(random_tensor,prime_tensor).numpy()

array([[2.1287455e+01, 1.3147267e+02, 5.6129913e+01, 6.3916152e+04,
        2.1830114e+08],
       [7.2987424e+07, 2.8109013e+11, 2.9172357e+13, 1.0150953e+17,
        3.1634389e+22],
       [1.3513035e+23, 8.4632214e+18, 4.2946381e+26, 9.7792548e+27,
        4.5219016e+28],
       [3.5735032e+36, 3.8123471e+35,           inf,           inf,
                  inf],
       [          inf,           inf,           inf,           inf,
                  inf]], dtype=float32)

## 5) Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [12]:
tf.argmax(random_tensor, axis=0).numpy()

array([2, 4, 4, 1, 1])

In [13]:
tf.argmin(random_tensor, axis=0).numpy()

array([1, 2, 0, 4, 2])

## 6) Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [18]:
# Sebelum
print(f"Size Awal : {random_tensor.shape} {prime_tensor.shape}" )

Size Awal : (5, 5) (5, 5)


In [19]:
# Setelah
concat_tensor_1 = tf.concat([random_tensor, prime_tensor], axis=0)
concat_tensor_2 = tf.concat([random_tensor, prime_tensor], axis=1)
print(f"Size yang sudah di concat (axis = 0) : {concat_tensor_1.shape}")
print(f"Size yang sudah di concat (axis = 1) : {concat_tensor_2.shape}")

Size yang sudah di concat (axis = 0) : (10, 5)
Size yang sudah di concat (axis = 1) : (5, 10)


## 7) Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [16]:
# Sorting random_tensor secara descending
tf.sort(random_tensor, direction="DESCENDING").numpy()

array([[5.7292266, 5.084854 , 4.858652 , 4.613833 , 2.2378907],
       [5.9685326, 5.4879904, 5.1130815, 4.714781 , 4.025921 ],
       [5.573825 , 4.476487 , 4.462555 , 4.070874 , 3.2475438],
       [4.894192 , 4.883642 , 4.827503 , 4.6798654, 4.009323 ],
       [5.704425 , 5.6030755, 5.4573894, 5.1000853, 4.4744415]],
      dtype=float32)

In [17]:
# Sorting prime_tensor secara descending
tf.sort(prime_tensor, direction="DESCENDING").numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)